### ISSUE TITLE
[REQ] fix license on GH

### ISSUE THREAD

**Issue by MarcoRavich** [maximoskp/cppAudioFX#1]
Hi there, 1st of all thanks for your awesome (voluntary) work !

Since we've doxed this git in our [HyMPS project](https://github.com/forart/HyMPS) (under [Effects](https://github.com/forart/HyMPS/blob/main/AudioFXs.md#audio---effects-) - [Guitar](https://github.com/forart/HyMPS/blob/main/Guitar.md#audio---effects---guitar-) - [DSPs](https://github.com/forart/HyMPS/blob/main/Guitar.md#dsps-) section), can you please fix licensing terms for it ?

Our "problem" is that the relative license badge isn't generated correctly:

![](https://flat.badgen.net/github/license/maximoskp/cppAudioFX)
(generator URL: https://flat.badgen.net/github/license/maximoskp/cppAudioFX)

This could be easily fixed by choosing a "correct" license file through the GH's wizard.

Although it may sounds like a minor aspect, this may help other devs to understand how reuse your code in other open projects and vice-versa that's a determining factor for the success and longevity of your project.

Last but not least, let us know how - in your opinion - we could improve our categorizations and links to resources in order to favor collaboration between developers (and therefore evolution) of listed projects.

Thanks in advance.

**Comment by maximoskp** [comment]
Great - thanks for including my project and for the comment about the license! I think I fixed it, please let me know if I did anything wrong.

Thanks!

**Comment by MarcoRavich** [comment]
Thanks for the timely fix!

As you can see (above too) the badge is now generated correctly.

Anyway we can't change placement of your project in our list 'cause - even though it claims to be a "C++ implementation" - GH reports "cmake" as the main git programming language...

https://github.com/forart/HyMPS/blob/main/Guitar.md#dsps-

This depends on our - recently introduced - dev-oriented sorting: we've recently decided to group+sort projects by multiple criterias - the "sorting chain" we adopted actually is: Section > Subsection > Language > License > Alphabetical - and will therefore showed in a slightly different way. 

Do you think this new approach could better foster collaboration between devs? Do you have any suggestions on this?

Thanks again and, if you like/need, let us know (by participating in [our discussions](https://github.com/forart/HyMPS/discussions) too) how can we better support listed projects.

Last but not least, Happy New Year !
